

services:
  postgres:
    image: postgres:16-alpine
    container_name: conduit-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database_development
    ports:
      - "5432:5432"
    volumes:
      - pgdata_vscode:/var/lib/postgresql/data

volumes:
  pgdata_vscode:
